trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'EduSync.API.sln'   # Change if your .sln file name or path is different
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x' # Use your actual .NET SDK version

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# -------------------------------
# Deploy to Azure Web App (Backend)
# -------------------------------
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'EduSyncConnection'        # From your service connections screenshot
    appType: 'webApp'
    appName: 'EduSync-Backpart'                  # From your App Service screenshot
    package: '$(build.artifactStagingDirectory)/**/*.zip'
    resourceGroupName: 'myresource'              # From your App Service screenshot
